### ISSUE TITLE
Not Connected to Internet - Installation Error

### ISSUE THREAD

**Issue by elc4br4** [Athena-OS/athena-iso#23]
![errrrrrrrrrrr](https://user-images.githubusercontent.com/87612464/207765470-d9880ca3-2cb7-467a-b304-2a74e97e6f28.png)

ON VIRTUAL BOX

**Comment by D3vil0p3r** [comment]
@elc4br4 The connection check on the installer is not done on Google domain. There could be some domain your network is blocking. What is the output of `sudo pacman -Syy`?

**Comment by elc4br4** [comment]
This is the output
![aaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/87612464/207921582-df0cf98a-f5bd-4e26-90f0-8c9a66939688.png)

I have tried the installation on other devices without virtualizing and I get the same error.

**Comment by D3vil0p3r** [comment]
@elc4br4 what if you run `ping http://example.com`? Can you run it with the installer opened for checking if the connection is shown as down?

**Comment by D3vil0p3r** [comment]
@elc4br4 I mean `http://example.com`, so writing `example` instead of `google` or `youtube`. The connection check by the installer is done not by ping but by https://doc.qt.io/qt-5/qnetworkaccessmanager.html#get. Maybe `http://example.com` cannot be reached for some reason.

Btw, let's try to do the following:
```
sudo nano /etc/calamares/modules/welcome.conf
```
Replace `internetCheckUrl:   "http://example.com"` with `internetCheckUrl:   "http://www.google.com"` or `internetCheckUrl:   "https://www.google.com"`. If it still does not work, delete `- internet` under `required` section.

**Comment by elc4br4** [comment]
Solved bro thank you 4 all!!!

Replacing internetCheckUrl: "http://example.com" with internetCheckUrl: "http://www.google.com".
