### ISSUE TITLE
Unable to fully install Athena OS onto a VMWare and VirtualBox. 

### ISSUE THREAD

**Issue by CreateM1nd** [Athena-OS/athena-iso#32]
I've been having issues with installing the OS as a Virtual Machine. 

I've tried both on VMWare and on Oracle Virtual Machine. They both have had the same issue. I'll post what it says when it wasn't able complete the installation. 

Have you been seeing this issue? Has anyone else submitted something similar? 

[Athena OS issue.odt](https://github.com/Athena-OS/athena-iso/files/10778303/Athena.OS.issue.odt)

**Comment by D3vil0p3r** [comment]
@CreateM1nd Hey, yes. It occurs because I updated some packages impacting the installation and now I'm creating a minor release that should work. Meanwhile come on Discord.

**Comment by D3vil0p3r** [comment]
@CreateM1nd the new ISO is out. Please, use it and let me know if it works. Remember that on Virtual Machines you dont need to install drivers (as NVIDIA) because VMware Workstation and Oracle VirtualBox don't support GPU Passthrough, so during the installation skip "Drivers" and "Drivers Nv" sections.
