### ISSUE TITLE
Implemented a new menu: PWNage! - Not abe to  use on lenevo ideadpad 520.

### ISSUE THREAD

**Issue by adsulshyam0000** [Athena-OS/athena-iso#4]
PenTOXIC Menu
PWNage Menu

Menu not available on ctrl+backspace.

**Comment by D3vil0per** [comment]
@adsulshyam0000 Try to run the following command in the terminal:
```
gsettings set org.gnome.shell disable-user-extensions false
```
If it works, please add this command at the end of the `/etc/profile.d/run-once.sh` script. In this way, if GNOME disables again your GNOME extensions (as PWNage and PenTOXIC), they are automatically enabled.
Let me know if it works.

**Comment by adsulshyam0000** [comment]
/home/athena $ gsettings set org.gnome.shell disable-user-extensions false
┌──[HQ🚀⚔️athena]
└──╼[👾]/home/athena $ 


Did as you mentioned, still no improvement for PenTOXIC Menu, PWNage Menu.

I tried them to invoke with ctrl + backspace.

Please let me know it this menus depends on shortcuts.

**Comment by D3vil0per** [comment]
@adsulshyam0000 I think backspace is the incorrect one. You should try with:
* CTRL + SPACE (the long keyboard button) for PenTOXIC
* CTRL + TAB for PWNage

**Comment by D3vil0per** [comment]
Solved the issue. The problem was related to the fact that at the first boot, the system was not connected to Internet, so these extensions have not been installed. For solving this, the startup script managing the installation of these extensions have been run and the extensions have been enabled by Extensions application.
