### ISSUE TITLE
How to fix this warnings 

### ISSUE THREAD

**Issue by adsulshyam0000** [Athena-OS/athena-iso#5]
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: bfa
==> WARNING: Possibly missing firmware for module: qed
==> WARNING: Possibly missing firmware for module: qla1280
==> WARNING: Possibly missing firmware for module: qla2xxx
==> WARNING: Possibly missing firmware for module: wd719x
==> WARNING: Possibly missing firmware for module: xhci_pci
  -> Running build hook: [keyboard]

**Comment by D3vil0per** [comment]
@adsulshyam0000 They are firmwares not in the perimeter of Athena. They are spawn only because of hooks of mkinitcpio that can work also without them. So we chose to not install them for optimizing the disk space.

In general, if you want to install them, you should find the related packages by Arch repositories (by pacman -S <package>) or AUR repository (by paru -S <package>)

**Comment by adsulshyam0000** [comment]
Thanks a lot for this information !!
