### ISSUE TITLE
Installation not working on Dual Boot

### ISSUE THREAD

**Issue by Aahtrenz** [Athena-OS/athena-iso#7]
I just boot Athena iso in my usb and tried to install the Athena everything I fiene I selected all the options and when I create new partitions one for ext4 at /, 2nd for swap, third for efi and then when I clicked on the install button the installation windows close ? And it threw me to the desktop screen nothing happened I tried again but still when I click on install the installation window closed and show me the desktop, kindly guide.

**Comment by D3vil0per** [comment]
Hey @Aahtrenz . According to the tests, your issue is related to the lack of space of Cowspace because this space is 256 MB sized. It is not an user fault but it is an Arch Linux community choice. When Cowspace is full, Calamares Installer is not able to work properly anymore. For solving this issue, you need only to close the installer, run the following command:
```
sudo mount -o remount,size=2G /run/archiso/cowspace
```
re-click again on "Install Athena!" button if Athena Welcome is still open, or just type `calamares_polkit` on the terminal.

Anyway with the next release I will make this process automated. We must just be sure this will solve your issue.

**Comment by D3vil0per** [comment]
I close this ticket because we verified that the method explained above worked.
