### ISSUE TITLE
[QUESTION]: Soooo, can somebody explain to me why I would ever use this vs you know...

### ISSUE THREAD

**Issue by dverbeeck** [Athena-OS/athena-iso#78]
Why would I, or any serious professional, consider using this distro rather than you know, just spinning up my own based upon Slackware, Alpine, Fedora or really anything else?? It looks like YET ANOTHER pastiche of tools with zero attempt at any unique type of integration or thought applied. 

Super goddamn lazy and I cannot for one moment believe this is taken seriously by anybody... not even the maintainers.

Kids, the only 'hacking tool' you need is your brain and an interactive shell. Everything else is just an accessory.

**Comment by D3vil0p3r** [comment]
Hey @dverbeeck give a look to https://athenaos.org/en/getting-started/athenaos/ and Cyber Resource section. It should have some stuff that could be different from other distros. PS: there are also technical tailored aspects (also at kernel level), so non-functional specifications

**Comment by Azguard-Cybernetics** [comment]
@dverbeeck your a complete idiotic jackass athena is better then kali in more ways then kali could be for one athena os can run as a daily drive while kali cant athena support more driver related issues then the kali team even bothered to fix with athena i dont have to spend hours setting up my pc looking for drivers and have bloated crap i dont even need. for one athena is the best one next to parrot while kali linux sucks

**Comment by dverbeeck** [comment]
Ok so.. first - I never claimed Kali was great. personally I run lfs kitted
out via ansible with whatever tools I need of the day.

Second, I don't see anyone in industry using this new dist - not that it
means anything in and of itself other than perhaps it's not yet been
accepted and honored for what ground it has broken.

Third - Azguard my friend: You've got some tires on ya calling anybody an
idiot when you spent the time cobbling together such a lengthy run on
sentence devoid of much real meaning. 'Better than Kali could ever be kali'
isn't really a high mark of esteem. Additionally if you need to have things
patched for you, maybe start with something simpler like Duplo blocks?
Your  response for the most part reads like that of a juvenile who
discovered the Internet for the first time during recess this afternoon.

**Comment by D3vil0p3r** [comment]
> Ok so.. first - I never claimed Kali was great. personally I run lfs kitted out via ansible with whatever tools I need of the day. Second, I don't see anyone in industry using this new dist - not that it means anything in and of itself other than perhaps it's not yet been accepted and honored for what ground it has broken.

I join only for this: the OS is simply new. I got several contacts from "Big Industries" but Athena is still not ready for that. We want to give something different, not a copy and paste of Kali/Parrot...

Btw if you have some good idea to evolve in that sense, join the project and our community

**Comment by Azguard-Cybernetics** [comment]
@dverbeeck first of all i was using kali for more then 6 years until up to last year you may think what you want you may have your opinion just like everyone else, but its people like you that makes it hard for new comers to choose a distro and recommend kali linux while athena tries to make it more easier while being a daily driver for people like me that needs a pen testing distro as a daily driver. i called you an idiot due to the fact that some people are looking for something like athena and they read comments and people like you that breaks a distro down without even trying it you compare it to kali linux that has its issues while new comers can use athena to get started people like you compare a distro that has driver issues and was not meant to run as a daily driver a new comer looses, why dont you try athena and leave a report because you are chasing new comers from something they mite need,.

**Comment by Azguard-Cybernetics** [comment]
@D3vil0p3r athena is great on my end its responding extremely well with my laptop the only issue i found was corrupted keyrings and the calamares installer that has an issue with the online install it fails at 69% of installation and after upgrade the athena welcomer does not work correctly like the HTB and the roles does not work but other then that is damn good i would really like it if it comes with openbox wm. plus i also like the xfce version..

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r athena is great on my end its responding extremely well with my laptop the only issue i found was corrupted keyrings and the calamares installer that has an issue with the online install it fails at 69% of installation and after upgrade the athena welcomer does not work correctly like the HTB and the roles does not work but other then that is damn good i would really like it if it comes with openbox wm. plus i also like the xfce version..

Calamares Installer is deprecated. We removed it and the current rolling ISO is using a dedicated installer called **Aegis**. Currently Aegis is based on a new installer RUST-based backend inspired by Jade but a temporary GUI that will be replaced in the near future with a better one that we are creating from scratch. Currently as WM I invite you to use Bspwm in Athena. There is also Hyprland as WM but currently it is in an experimental phase and not stable because based on the new Aylur's Gtk Shell (AGS) and we need some time to make it usable.

Please guys, be polite on your posts.

**Comment by Azguard-Cybernetics** [comment]
> > @D3vil0p3r athena is great on my end its responding extremely well with my laptop the only issue i found was corrupted keyrings and the calamares installer that has an issue with the online install it fails at 69% of installation and after upgrade the athena welcomer does not work correctly like the HTB and the roles does not work but other then that is damn good i would really like it if it comes with openbox wm. plus i also like the xfce version..
> 
> Calamares Installer is deprecated. We removed it and the current rolling ISO is using a dedicated installer called **Aegis**. Currently Aegis is based on a new installer RUST-based backend inspired by Jade but a temporary GUI that will be replaced in the near future with a better one that we are creating from scratch. Currently as WM I invite you to use Bspwm in Athena. There is also Hyprland as WM but currently it is in an experimental phase and not stable because based on the new Aylur's Gtk Shell (AGS) and we need some time to make it usable.
> 
> Please guys, be polite on your posts.

okay...great job on Athena by the way its what i needed i will stick with the current one for now gnome runs better for me very responsive unlike others which is weird, i will try to be polite next time.

**Comment by D3vil0p3r** [comment]
Others do you mean other desktop environments proposed in Athena?

**Comment by Azguard-Cybernetics** [comment]
> Others do you mean other desktop environments proposed in Athena?

gnome desktop environments from ubuntu, fedora and more i was using kali with gnome and it used alot of ram and cpu but what you did with gnome is awesome it uses 1.3GB to 1.8GB  and 50% of cpu and im running a low end AMD laptop with a Redeon R3 4GB Ram.  i have not yet tried other environments in Athena due to the online install failure but i would like to but so far gnome in Athena is light and responsive atleast for me.

**Comment by D3vil0p3r** [comment]
> > Others do you mean other desktop environments proposed in Athena?
> 
> gnome desktop environments from ubuntu, fedora and more i was using kali with gnome and it used alot of ram and cpu but what you did with gnome is awesome it uses 1.3GB to 1.8GB and 50% of cpu and im running a low end AMD laptop with a Redeon R3 4GB Ram. i have not yet tried other environments in Athena due to the online install failure but i would like to but so far gnome in Athena is light and responsive atleast for me.

It occurs because Athena uses a "particular" GNOME environment... And don't worry for failing install. The new installer is built to be more fault tolerant.

**Comment by shard77** [comment]
I wanted to add something to this, @dverbeek. 
Athena is yet not ready, for industry deployment, as D3v pointed out. Our goal is not to make a mirror of all the existing distros, we have clear goals that we want to reach, and we are ready to innovate. Tough, development takes time, we are a small team, working on this whenever we have some free time. I don't consider AthenaOS to be daily-drivable yet. I also don't recommend to do so, simply because we are actively pushing things, changing core aspects of the system, implementing new features etc.. Hope this helps.
