### ISSUE TITLE
[BUG]: Alternative kb mappings cannot be tested in the installer

### ISSUE THREAD

**Issue by munkinut** [Athena-OS/athena-iso#84]
### Athena OS version

Athena OS Polias

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.5.10-hardened1-1-hardened

### Involved software

Installer in Polias

### Repro steps

Go the the installation process in the Installer.  Get to the language and kb mappings.  Search for and select a gb keyboard.  Go to the test area and check the mappings for #£@ etc. 

### Expected behavior

I want to see how the text looks with the selected language and keyboard settings.

### Actual behavior

The test area shows that the kb mappings have not changed.

**Comment by D3vil0p3r** [comment]
Fixed: https://github.com/Athena-OS/aegis-gui/commit/66416a64a0470d039c58d0876e9219c7f29c1bac

I will ship a new ISO with this fix. If you want to test it on the current ISO, you can run a Live Environment (i.e., in a VM) and upgrade the system by `sudo pacman -Syyu` in order to have the latest installer version. In order to use pacman in Live Environment, you need first to set keys:
```
sudo pacman-key --init
sudo pacman-key --populate
sudo pacman -Syyu
```
Thank you for your report.
